name: Deploy Static Website
#comment for workflow refresh - more comments
on:
  push:
    paths:
      - 'HTML/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Echo first 5 characters of storage key (for debug)
        run: echo "${AZURE_STORAGE_KEY:0:5}*****"
        env:
          AZURE_STORAGE_KEY: ${{ secrets.CRC_AZURE_BLOB }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload static files to Azure Blob Storage
        run: |
          az storage blob upload-batch \
            --account-name cjdstorageaccount \
            --destination '$web' \
            --source HTML \
            --auth-mode key \
            --overwrite
        env:
          AZURE_STORAGE_KEY: ${{ secrets.CRC_AZURE_BLOB }}
