name: Deploy Azure Function
#comment
on:
  push:
    paths:
      - 'visitor-counter/**'
      - '.github/workflows/deploy-function.yml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd visitor-counter
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          zip -r visitor-counter.zip .

      - name: Install test coverage tools
        run: |
          cd visitor-counter
          pip install pytest-cov

      - name: Run unit tests
        run: |
          cd visitor-counter
            --cov=visitor_counter --cov-fail-under=80

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: visitor-counter/htmlcov


      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: cjdvisitorcounterfunc
          package: visitor-counter/visitor-counter.zip
          publish-profile: ${{ secrets.CRC_FUNCTIONAPP_PUBLISH }}
