name: Deploy Static Website

on:
  push:
    paths:
      - 'HTML/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload static files to Azure Blob Storage
        run: |
          az storage blob upload-batch \
            --account-name cjdstorageaccount \
            --destination '$web' \
            --source HTML \
            --overwrite \
            --auth-mode key
        env:
          AZURE_STORAGE_KEY: ${{ secrets.CRC_AZURE_BLOB }}
